### ISSUE TITLE
docker bulid issues:'/bin/sh -c /bin/bash -l -c "bundle install --system"'

### ISSUE THREAD

**Issue by KunPengRen** [intrigueio/intrigue-core#65] opened 2017-12-29 10:15 UTC
Fetching sidekiq-unique-jobs 5.0.10
Installing sidekiq-failures 1.0.0
Installing sidekiq-unique-jobs 5.0.10
Installing nokogiri 1.8.1 with native extensions
Fetching whois-parser 1.0.1
Installing whois-parser 1.0.1
Fetching aws-sdk-resources 2.10.64
Installing aws-sdk-resources 2.10.64
Killed
The command '/bin/sh -c /bin/bash -l -c "bundle install --system"' returned a non-zero code: 137

**Comment by jcran** [comment] 2018-02-05 20:17
Usually caused by running out of memory: https://github.com/docker/compose/issues/1554. Try it on a bigger box, and ping here if you run into issues. Closing for now.

**Closed by jcran** 2018-02-05 20:17 UTC
